switches to uberjar for dependency packaging

diff --git a/bin/gnocchi-shell b/bin/gnocchi-shell
--- a/bin/gnocchi-shell
+++ b/bin/gnocchi-shell
@@ -19,44 +19,39 @@
 
 set -e
 
-# Figure out where ADAM is installed
+# Figure out where GNOCCHI is installed
 SCRIPT_DIR="$(cd `dirname $0`/..; pwd)"
 
 # does the user have GNOCCHI_OPTS set? if yes, then warn
-# not sure if this applied for gnocchi shell
-if [[ $DD == False && -n "$GNOCCHI_OPTS" ]]; then
+if [[ -z $@ && -n "$GNOCCHI_OPTS" ]]; then
     echo "WARNING: Passing Spark arguments via GNOCCHI_OPTS was recently removed."
     echo "Run gnocchi-shell instead as gnocchi-shell <spark-args>"
 fi
 
-# Find ADAM cli assembly jar
-ADAM_CLI_JAR=
+# Find GNOCCHI cli assembly jar
+GNOCCHI_CLI_JAR=
 if [ -d "$SCRIPT_DIR/repo" ]; then
   ASSEMBLY_DIR="$SCRIPT_DIR/repo"
 else
-  ASSEMBLY_DIR="$SCRIPT_DIR/adam-assembly/target"
+  ASSEMBLY_DIR="$SCRIPT_DIR/gnocchi-cli/target"
 fi
 
-#num_jars="$(ls -1 "$ASSEMBLY_DIR" | grep "^adam_[0-9A-Za-z\.-]*\.jar$" | grep -v javadoc | grep -v sources | wc -l)"
-#if [ "$num_jars" -eq "0" ]; then
-#  echo "Failed to find ADAM assembly in $ASSEMBLY_DIR." 1>&2
-#  echo "You need to build ADAM before running this program." 1>&2
-#  exit 1
-#fi
+num_jars="$(ls -1 "$ASSEMBLY_DIR" | grep "^gnocchi-cli_[0-9A-Za-z\.-]*\.jar$" | grep -v javadoc | grep -v sources | wc -l)"
+if [ "$num_jars" -eq "0" ]; then
+  echo "Failed to find GNOCCHI assembly in $ASSEMBLY_DIR." 1>&2
+  echo "You need to build GNOCCHI before running this program." 1>&2
+  exit 1
+fi
 
-#ASSEMBLY_JARS="$(ls -1 "$ASSEMBLY_DIR" | grep "^adam_[0-9A-Za-z\.-]*\.jar$" | grep -v javadoc | grep -v sources || true)"
-#if [ "$num_jars" -gt "1" ]; then
-#  echo "Found multiple M cli assembly jars in $ASSEMBLY_DIR:" 1>&2
-#  echo "$ASSEMBLY_JARS" 1>&2
-#  echo "Please remove all but one jar." 1>&2
-#  exit 1
-#fi
+ASSEMBLY_JARS="$(ls -1 "$ASSEMBLY_DIR" | grep "^gnocchi-cli_[0-9A-Za-z\.-]*\.jar$" | grep -v javadoc | grep -v sources || true)"
+if [ "$num_jars" -gt "1" ]; then
+  echo "Found multiple GNOCCHI cli assembly jars in $ASSEMBLY_DIR:" 1>&2
+  echo "$ASSEMBLY_JARS" 1>&2
+  echo "Please remove all but one jar." 1>&2
+  exit 1
+fi
 
-GNOCCHI_JARS=$("$SCRIPT_DIR"/bin/compute-gnocchi-jars.sh)
-GNOCCHI_CLI_JAR=${GNOCCHI_JARS##*,}
-GNOCCHI_JARS=$(echo "$GNOCCHI_JARS" | rev | cut -d',' -f2- | rev)
-GNOCCHI_CORE_JAR=${GNOCCHI_JARS%%,*}
-
+GNOCCHI_CLI_JAR="${ASSEMBLY_DIR}/${ASSEMBLY_JARS}"
 
 if [ -z "$SPARK_HOME" ]; then
   SPARK_SHELL=$(which spark-shell || echo)
@@ -73,5 +68,5 @@ echo "Using SPARK_SHELL=$SPARK_SHELL"
 "$SPARK_SHELL" \
     --conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
     --conf spark.kryo.registrator=org.bdgenomics.adam.serialization.ADAMKryoRegistrator \
-    --jars ${GNOCCHI_CLI_JAR},${GNOCCHI_CORE_JAR} \
+    --jars ${GNOCCHI_CLI_JAR} \
     "$@"
diff --git a/bin/gnocchi-submit b/bin/gnocchi-submit
--- a/bin/gnocchi-submit
+++ b/bin/gnocchi-submit
@@ -52,15 +52,35 @@ fi
 # Figure out where GNOCCHI is installed
 SCRIPT_DIR="$(cd `dirname $0`/..; pwd)"
 
-# Get list of required jars for GNOCCHI
-GNOCCHI_JARS=$("$SCRIPT_DIR"/bin/compute-gnocchi-jars.sh)
+GNOCCHI_CLI_JAR=
+if [ -d "$SCRIPT_DIR/repo" ]; then
+  ASSEMBLY_DIR="$SCRIPT_DIR/repo"
+else
+  ASSEMBLY_DIR="$SCRIPT_DIR/gnocchi-cli/target"
+fi
 
-# Split out the CLI jar, since it will be passed to Spark as the "primary resource".
-GNOCCHI_CLI_JAR=${GNOCCHI_JARS##*,}
-GNOCCHI_JARS=$(echo "$GNOCCHI_JARS" | rev | cut -d',' -f2- | rev)
+num_jars="$(ls -1 "$ASSEMBLY_DIR" | grep "^gnocchi_cli[0-9A-Za-z\.-]*\.jar$" | grep -v javadoc | grep -v sources | wc -l)"
+if [ "$num_jars" -eq "0" ]; then
+  echo "Failed to find GNOCCHI cli assembly in $ASSEMBLY_DIR." 1>&2
+  echo "You need to build GNOCCHI before running this program." 1>&2
+  exit 1
+fi
 
-# append GNOCCHI_JARS to the --jars option, if any
-SPARK_ARGS=$("$SCRIPT_DIR"/bin/append_to_option.py , --jars $GNOCCHI_JARS $SPARK_ARGS)
+ASSEMBLY_JARS="$(ls -1 "$ASSEMBLY_DIR" | grep "^gnocchi_cli[0-9A-Za-z\.-]*\.jar$" | grep -v javadoc | grep -v sources || true)"
+if [ "$num_jars" -gt "1" ]; then
+  echo "Found multiple GNOCCHI cli assembly jars in $ASSEMBLY_DIR:" 1>&2
+  echo "$ASSEMBLY_JARS" 1>&2
+  echo "Please remove all but one jar." 1>&2
+  exit 1
+fi
+
+GNOCCHI_CLI_JAR="${ASSEMBLY_DIR}/${ASSEMBLY_JARS}"
+
+# Allow main class to be overridden
+if [ -z "$GNOCCHI_MAIN" ]; then
+  GNOCCHI_MAIN="net.fnothaft.gnocchi.cli.GnocchiMain"
+fi
+echo "Using GNOCCHI_MAIN=$GNOCCHI_MAIN"
 
 # Find spark-submit script
 if [ -z "$SPARK_HOME" ]; then
@@ -80,9 +100,9 @@ echo "Using SPARK_SUBMIT=$SPARK_SUBMIT"
   --conf spark.serializer=org.apache.spark.serializer.KryoSerializer \
   --conf spark.kryo.registrator=org.bdgenomics.adam.serialization.ADAMKryoRegistrator \
   --conf spark.kryo.registrationRequired=false \
-  $SPARK_ARGS \
-  $GNOCCHI_CLI_JAR \
-  $GNOCCHI_ARGS
+  "${SPARK_ARGS[@]}" \
+  "$GNOCCHI_CLI_JAR" \
+  "${GNOCCHI_ARGS[@]}"
 echo "Done submiting the args to GnochiMain.main()"
   # org.bdgenomics.adam.serialization.ADAMKryoRegistrator
   # This was the old one. net.fnothaft.gnocchi.GnocchiKryoRegistrator
